name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the problem you're trying to solve or the use case for this feature.
      placeholder: |
        I'm trying to...
        Currently, I have to...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or how you'd like this feature to work.
      placeholder: |
        I would like to be able to...
        The API could look like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or workarounds you've considered.
      placeholder: |
        I've tried...
        Another approach could be...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, code examples, or screenshots about the feature request.
